# PyMOL Visualization Script
# Generated by hole_pymol.py (using official HOLE sph_process)

# 색상 공간: CMYK
set color_space, cmyk

# 커스텀 색상 정의 (CMYK)
set_color grey70, [0.0, 0.0, 0.0, 0.3]  # CMYK: K=30%
set_color orange, [0.0, 0.5, 1.0, 0.0]  # CMYK: M=50%, Y=100%

# 배경: 흰색
bg_color white

# 1. 단백질 로드 (Cartoon) - 먼저 로드
load /tmp/hole_rcsb_6uz3_piezo1_out_1oamkokm/rcsb_6uz3_piezo1_out.pdb, protein_cartoon
hide everything, protein_cartoon
show cartoon, protein_cartoon
set transparency, 0.6, protein_cartoon
color orange, protein_cartoon

# 2. 단백질 로드 (Surface) - 나중에 로드 (위에 렌더링)
load /tmp/hole_rcsb_6uz3_piezo1_out_1oamkokm/rcsb_6uz3_piezo1_out.pdb, protein_surface
hide everything, protein_surface
show surface, protein_surface
set transparency, 0.8, protein_surface
color grey70, protein_surface

# 3. 기공 표면 로드
load /tmp/hole_rcsb_6uz3_piezo1_out_1oamkokm/rcsb_6uz3_piezo1_out_pore_surface.pdb, pore
hide everything, pore
show spheres, pore
set sphere_scale, 0.25, pore

# 4. 기공 반경별 색상 (HOLE 표준)
# 반경 범위: 1.53 - 12.31 Å
color red, resn POR      # 좁음 (< 1.15 Å)
color green, resn POG    # 중간 (1.15-2.30 Å)
color blue, resn POB     # 넓음 (> 2.30 Å)
color yellow, resn CEN   # 중심선

# 5. 시각화 설정
set ray_shadows, 1
set antialias, 2
set cartoon_transparency, 0.6, protein_cartoon
set surface_quality, 1

# 6. 렌더링 순서 명시 (아래부터: Cartoon -> Surface -> Pore)
order protein_cartoon protein_surface pore

# 7. 뷰 조정
zoom all
center pore

print("=== HOLE Visualization ===")
print("Color space: CMYK")
print("Protein (Surface): grey70 (K=30%), 80% transparent")
print("Protein (Cartoon): orange (M=50%, Y=100%), 60% transparent")
print("Pore surface: colored by radius (HOLE standard)")
print("  RED    - Too narrow (< 1.15 Å)")
print("  GREEN  - Single water (1.15-2.30 Å)")
print("  BLUE   - Wide pore (> 2.30 Å)")
print("  YELLOW - Center line")
